TRAIN_TASKS = [
    "abstract_narrative_understanding",
    "anachronisms",
    # "analogical_similarity", !
    "analytic_entailment",
    "arithmetic",
    # "authorship_verification", !
    "bbq_lite_json",
    # "bbq_lite",
    # "bias_from_probabilities",
    "causal_judgment",
    "cause_and_effect",
    "checkmate_in_one",
    "code_line_description",
    "color",
    # "com2sense",
    "common_morpheme",
    "conceptual_combinations",
    # "context_definition_alignment",
    "contextual_parametric_knowledge_conflicts",
    # "convinceme",
    "crass_ai",
    "cryobiology_spanish",
    "cs_algorithms",
    "date_understanding",
    "disambiguation_qa",
    "discourse_marker_prediction",
    # "diverse_social_bias",
    "dyck_languages",
    # "dynamic_counting",
    "elementary_math_qa",
    "emoji_movie",
    "emojis_emotion_prediction",
    "empirical_judgments",
    "english_russian_proverbs",
    "entailed_polarity",
    "epistemic_reasoning",
    "evaluating_information_essentiality",
    "fact_checker",
    # "factuality_of_summary",
    "fantasy_reasoning",
    "figure_of_speech_detection",
    # "forecasting_subquestions",
    # "gender_sensitivity_chinese",
    "general_knowledge",
    "geometric_shapes",
    "goal_step_wikihow",
    "gre_reading_comprehension",
    "hhh_alignment",
    "hindu_knowledge",
    "hinglish_toxicity",
    "human_organs_senses",
    "identify_math_theorems",
    "identify_odd_metaphor",
    "implicatures",
    "implicit_relations",
    # "indic_cause_and_effect", !
    "international_phonetic_alphabet_nli",
    "intersect_geometry",
    # "kanji_ascii", !
    # "known_unknowns", !
    # "logic_grid_puzzle", !
    # "logical_args", !
    # "logical_deduction", !
    # "logical_fallacy_detection", !
    # "long_context_integration",
    # "minute_mysteries_qa", !
    # "misconceptions_russian", !
    # "misconceptions", !
    # "moral_permissibility", !
    # "multiemo",
    "navigate",
    "nonsense_words_grammar",
    "novel_concepts",
    "odd_one_out",
    # "parsinlu_qa", !
    "penguins_in_a_table",
    "periodic_elements",
    "persian_idioms",
    "phrase_relatedness",
    "physics",
    "play_dialog_same_or_different",
    "presuppositions_as_nli",
    # "question_answer_creation",
    "question_selection",
    "real_or_fake_text",
    "reasoning_about_colored_objects",
    "rhyming",
    "riddle_sense",
    "ruin_names",
    "salient_translation_error_detection",
    # "self_awareness",
    # "self_evaluation_courtroom",
    # "self_evaluation_tutoring",
    "similarities_abstraction",
    "simple_ethical_questions",
    "snarks",
    "social_iqa",
    "social_support",
    "sports_understanding",
    "strange_stories",
    "strategyqa",
    # "subject_verb_agreement",
    "suicide_risk",
    "swahili_english_proverbs",
    "symbol_interpretation",
    # "talkdown",
    "temporal_sequences",
    "timedial",
    "tracking_shuffled_objects",
    # "truthful_qa",
    # "twenty_questions",
    "understanding_fables",
    "unit_conversion",
    # "unqover",
    "vitaminc_fact_verification",
    "what_is_the_tao",
    "which_wiki_edit",
    # "wino_x_german",
]

TEST_TASKS = [
    # "boolean_expressions", #
    "crash_blossom",
    "dark_humor_detection",
    "english_proverbs",
    "entailed_polarity_hindi",
    "formal_fallacies_syllogisms_negation",
    # "gender_sensitivity_english", #
    "hyperbaton",
    "intent_recognition",
    "irony_identification",
    "kannada",
    "key_value_maps",
    "language_identification",
    "logical_sequence",
    "mathematical_induction",
    "medical_questions_russian",
    "metaphor_boolean",
    "metaphor_understanding",
    "movie_dialog_same_or_different", 
    "movie_recommendation", 
    "physical_intuition",
    # "protein_interacting_sites", #
    "sentence_ambiguity",
    # "simple_arithmetic_json_multiple_choice", #
    "swedish_to_german_proverbs",
    # "training_on_test_set", #
    "undo_permutation",
    "unit_interpretation",
    # "web_of_lies", #
    "winowhy",
]

ETHAN_TASKS = [
    "abstract_narrative_understanding",
    "anachronisms",
    "analogical_similarity",
    "analytic_entailment",
    "arithmetic",
    "authorship_verification",
    "bbq_lite_json",
    "causal_judgment",
    "cause_and_effect",
    "checkmate_in_one",
    "code_line_description",
    "color",
    "common_morpheme",
    "conceptual_combinations",
    "contextual_parametric_knowledge_conflicts",
    "crass_ai",
    "cryobiology_spanish",
    "cs_algorithms",
    "date_understanding",
    "disambiguation_qa",
    "discourse_marker_prediction",
    "dyck_languages",
    "elementary_math_qa",
    "emoji_movie",
    "emojis_emotion_prediction",
    "empirical_judgments",
    "english_russian_proverbs",
    "entailed_polarity",
    "epistemic_reasoning",
    "evaluating_information_essentiality",
    "fact_checker",
    "fantasy_reasoning",
    "figure_of_speech_detection",
    "general_knowledge",
    "geometric_shapes",
    "goal_step_wikihow",
    "gre_reading_comprehension",
    "hhh_alignment",
    "hindu_knowledge", 
    "hinglish_toxicity",
    "human_organs_senses",
    "identify_math_theorems",
    "identify_odd_metaphor",
    "implicatures",
    "implicit_relations",
    "indic_cause_and_effect",
    "international_phonetic_alphabet_nli",
    "intersect_geometry",
]

SUNIL_TASKS = [
    "kanji_ascii",
    "known_unknowns",
    "logic_grid_puzzle",
    "logical_args",
    "logical_deduction",
    "logical_fallacy_detection",
    "minute_mysteries_qa",
    "misconceptions",
    "misconceptions_russian",
    "moral_permissibility",
    "navigate",
    "nonsense_words_grammar",
    "novel_concepts",
    "odd_one_out",
    "parsinlu_qa",
    "penguins_in_a_table",
    "periodic_elements",
    "persian_idioms",
    "phrase_relatedness",
    "physics",
    "play_dialog_same_or_different",
    "presuppositions_as_nli",
    "question_selection",
    # "real_or_fake_text", !
    "reasoning_about_colored_objects",
    "rhyming",
    "riddle_sense",
    "ruin_names",
    "salient_translation_error_detection",
    "similarities_abstraction",
    "simple_ethical_questions",
    "snarks",
    "social_iqa",
    "social_support",
    "sports_understanding",
    "strange_stories",
    "strategyqa",
    "suicide_risk",
    "swahili_english_proverbs",
    "symbol_interpretation",
    "temporal_sequences",
    "timedial",
    "tracking_shuffled_objects",
    "understanding_fables",
    "unit_conversion",
    "vitaminc_fact_verification",
    "what_is_the_tao",
    "which_wiki_edit",
]

IGNORED_TASKS = ["kanji_ascii", "parsinlu_qa"]

JSON_SCHEMA = """
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "inputs": {
      "type": "string"
    },
    "targets": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "multiple_choice_targets": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": ["inputs", "targets", "multiple_choice_targets"]
}
```"""
